### PR TITLE
Mention signalbackup-tools availability in nixpkgs

### PR DESCRIPTION
**Pull request by malob**
I [recently added](https://github.com/NixOS/nixpkgs/pull/150763) `signalbackup-tools` to `nixpkgs`, so its now available to install using the Nix package manager on both Linux and macOS.

### CODE REVIEW

**Comment by malob** [comment]
@bepaald, anything I can do to help get this merged?

**Comment by bepaald** [comment]
Hi! Thanks for your contribution. I have been extremely busy lately, so it's taking a while. In the meantime, my local branch is in a half-finished state, which is why I'm not just quickly pushing now (though this is of course because I'm not correctly using all that git has to offer).

I'm not completely sure if I'm going to apply your changes exactly like this, it seems a bit too much to give nix a separate entry next to windows, mac and linux, but I also haven't thought of a neater way to mention it, so I might still do it. Either way, I will definitely mention the availability through nixpkgs, it seems to be especially useful for macOS users. Hopefully this weekend, next weekend at the latest.

**Comment by malob** [comment]
Sounds good!

(Didn't mean to rush you or anything. Let me know if there's anything I can do to help.)

**Comment by bepaald** [comment]
Hi, sorry for the delay, I've finally pushed all the things I did lately, and the nixpkg is now mentioned in the readme. Hopefully the way I did it works for you. If not, feel free to suggest some changes, I'll consider them.

**Comment by malob** [comment]
lgtm, thanks!

**Pull request closed without merging**
